# Generated by Django 4.2.1 on 2023-06-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("F", "First"),
                            ("S", "Second"),
                            ("T", "Third"),
                            ("F", "Home Run"),
                        ],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.player",
                    ),
                ),
            ],
        ),
    ]
